# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /mnt/analysis/e21069/JH/sw/miniconda3/envs/root-analysis/bin/cmake

# The command to remove a file.
RM = /mnt/analysis/e21069/JH/sw/miniconda3/envs/root-analysis/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/analysis/e21069/JH/ldf2root

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/analysis/e21069/JH/ldf2root

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/mnt/analysis/e21069/JH/sw/miniconda3/envs/root-analysis/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/mnt/analysis/e21069/JH/sw/miniconda3/envs/root-analysis/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/mnt/analysis/e21069/JH/sw/miniconda3/envs/root-analysis/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/mnt/analysis/e21069/JH/sw/miniconda3/envs/root-analysis/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/mnt/analysis/e21069/JH/sw/miniconda3/envs/root-analysis/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/mnt/analysis/e21069/JH/sw/miniconda3/envs/root-analysis/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/mnt/analysis/e21069/JH/sw/miniconda3/envs/root-analysis/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/mnt/analysis/e21069/JH/sw/miniconda3/envs/root-analysis/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/analysis/e21069/JH/ldf2root/CMakeFiles /mnt/analysis/e21069/JH/ldf2root//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/analysis/e21069/JH/ldf2root/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ldf2root

# Build rule for target.
ldf2root: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ldf2root
.PHONY : ldf2root

# fast build rule for target.
ldf2root/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ldf2root.dir/build.make CMakeFiles/ldf2root.dir/build
.PHONY : ldf2root/fast

#=============================================================================
# Target rules for targets named DDAS_root

# Build rule for target.
DDAS_root: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DDAS_root
.PHONY : DDAS_root

# fast build rule for target.
DDAS_root/fast:
	$(MAKE) $(MAKESILENT) -f core/CMakeFiles/DDAS_root.dir/build.make core/CMakeFiles/DDAS_root.dir/build
.PHONY : DDAS_root/fast

#=============================================================================
# Target rules for targets named DDASRoot

# Build rule for target.
DDASRoot: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DDASRoot
.PHONY : DDASRoot

# fast build rule for target.
DDASRoot/fast:
	$(MAKE) $(MAKESILENT) -f core/CMakeFiles/DDASRoot.dir/build.make core/CMakeFiles/DDASRoot.dir/build
.PHONY : DDASRoot/fast

#=============================================================================
# Target rules for targets named DDASRootLegacy_root

# Build rule for target.
DDASRootLegacy_root: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DDASRootLegacy_root
.PHONY : DDASRootLegacy_root

# fast build rule for target.
DDASRootLegacy_root/fast:
	$(MAKE) $(MAKESILENT) -f core/CMakeFiles/DDASRootLegacy_root.dir/build.make core/CMakeFiles/DDASRootLegacy_root.dir/build
.PHONY : DDASRootLegacy_root/fast

#=============================================================================
# Target rules for targets named DDASRootLegacy

# Build rule for target.
DDASRootLegacy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DDASRootLegacy
.PHONY : DDASRootLegacy

# fast build rule for target.
DDASRootLegacy/fast:
	$(MAKE) $(MAKESILENT) -f core/CMakeFiles/DDASRootLegacy.dir/build.make core/CMakeFiles/DDASRootLegacy.dir/build
.PHONY : DDASRootLegacy/fast

#=============================================================================
# Target rules for targets named ldf2rootCore

# Build rule for target.
ldf2rootCore: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ldf2rootCore
.PHONY : ldf2rootCore

# fast build rule for target.
ldf2rootCore/fast:
	$(MAKE) $(MAKESILENT) -f core/CMakeFiles/ldf2rootCore.dir/build.make core/CMakeFiles/ldf2rootCore.dir/build
.PHONY : ldf2rootCore/fast

ldf2root.o: ldf2root.cpp.o
.PHONY : ldf2root.o

# target to build an object file
ldf2root.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ldf2root.dir/build.make CMakeFiles/ldf2root.dir/ldf2root.cpp.o
.PHONY : ldf2root.cpp.o

ldf2root.i: ldf2root.cpp.i
.PHONY : ldf2root.i

# target to preprocess a source file
ldf2root.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ldf2root.dir/build.make CMakeFiles/ldf2root.dir/ldf2root.cpp.i
.PHONY : ldf2root.cpp.i

ldf2root.s: ldf2root.cpp.s
.PHONY : ldf2root.s

# target to generate assembly for a file
ldf2root.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ldf2root.dir/build.make CMakeFiles/ldf2root.dir/ldf2root.cpp.s
.PHONY : ldf2root.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... DDASRootLegacy_root"
	@echo "... DDAS_root"
	@echo "... DDASRoot"
	@echo "... DDASRootLegacy"
	@echo "... ldf2root"
	@echo "... ldf2rootCore"
	@echo "... ldf2root.o"
	@echo "... ldf2root.i"
	@echo "... ldf2root.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

